SystemManage/SystemManage/Controllers/UploadFileController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using SystemManage.Database;
using SystemManage.Models;
using SystemManage.Controllers;
using System.Diagnostics;

namespace SystemManage.Controllers
{
    public class UploadFileController : Controller
    {
        Entities db = new Entities();
        // GET: Upload
        public ActionResult Index()
        {
            if ((Session["userID"]) == null)
            {
                return RedirectToAction("Index", "Login");
            }
            return View();
        }
        [HttpPost]
        public ActionResult Index(DocumentModel model)
        {
            if (ModelState.IsValid)
            {
                int projectID = Convert.ToInt32(Session["ProjectID"]);
                Document d = new Document();
                var data = Process(model.AttachFile);
                string[] txt = data.Split(",".ToCharArray());
                string fileName = txt[1];
                string path = txt[0];
                d.DocumentName = model.DocumentName;
                d.DocumentDetail = model.DocumentDetail;
                d.AttachFile = path;
                d.AttachShow = fileName;
                d.CreateDate = DateTime.Now;
                d.CreateBy = Convert.ToInt32(Session["userID"]);
                d.Project_ID = projectID;
                db.Documents.Add(d);
                db.SaveChanges();
                return RedirectToAction("ShowDocument");
            }
            return View();
        }
        public ActionResult ShowDocument()
        {
            if ((Session["userID"]) == null)
            {
                return RedirectToAction("Index", "Login");
            }
            int ProjectID = Convert.ToInt32(Session["ProjectID"]);
            List<DocumentModel> DocumentList = new List<DocumentModel>();
            DocumentModel model = new DocumentModel();
            var d = db.Documents.Where(m => m.Project_ID == ProjectID).ToList();
            var pm = db.Projects.Where(m => m.ProjectID == ProjectID).FirstOrDefault();
            model.CreateBy = pm.CreateBy;
            model.Project_Status = pm.Status;
            foreach (var item in d)
            {
                string[] Type = item.AttachShow.Split(".".ToCharArray());
                DocumentList.Add(new DocumentModel {
                    DocumentID = item.DocumentID,
                    DocumentName = item.DocumentName,
                    AttachShow = Type[0],
                    pathFormView = item.AttachFile,
                    Type = Type[1],
                    CreateDate = item.CreateDate
                });
            }
            ViewBag.DataList = DocumentList;
            return View(model);
        }
        public ActionResult EditDocument(DocumentModel model)
        {
            var d = db.Documents.Where(m => m.DocumentID == model.DocumentID).FirstOrDefault();
            d.DocumentName = model.DocumentName;
            d.DocumentDetail = model.DocumentDetail;
            var data = Process(model.AttachFile);
            string[] txt = data.Split(",".ToCharArray());
            string fileName = txt[0];
            string path = txt[1];
            d.AttachShow = fileName;
            d.AttachFile = path;
            db.SaveChanges();
            return RedirectToAction("ShowDocument");
        }
        public ActionResult DetailDocument(int DocumentID)
        {
            if ((Session["userID"]) == null)
            {
                return RedirectToAction("Index", "Login");
            }
            var d = db.Documents.Where(m => m.DocumentID == DocumentID).FirstOrDefault();
            DocumentModel model = new DocumentModel();
            model.DocumentID = d.DocumentID;
            model.DocumentName = d.DocumentName;
            model.DocumentDetail = d.DocumentDetail;
            model.AttachShow = d.AttachShow;
            model.ShowPath = d.AttachFile;
            model.CreateBy = d.CreateBy;
            return View(model);
        }
        public ActionResult DeleteDocument(int DocumentID)
        {
            var d = db.Documents.Where(m => m.DocumentID == DocumentID).FirstOrDefault();
            System.IO.File.Delete("C:/Users/SWNGMN/source/repos/SystemManage/SystemManage/SystemManage" + d.AttachFile);
            db.Documents.Remove(d);
            db.SaveChanges();
            return RedirectToAction("ShowDocument");
        }
        private bool isValidContentType(string contentType)
        {
            return contentType.Equals("image/png") || contentType.Equals("image/jpg") || contentType.Equals("application/pdf") || contentType.Equals("image/jpeg");
        }

        private bool isValidContentLength(int contentLength)
        {
            return ((contentLength / 1024) / 1024) < 1; // 1MB
        }
        public string Process(HttpPostedFileBase photo)
        {
            if (!isValidContentType(photo.ContentType))
            {
                ViewBag.Error = "เฉพาะไฟล์ jpg png pdf";
                return ("Error");
            }
            else if (!isValidContentLength(photo.ContentLength))
            {
                ViewBag.Error = "ไฟล์มีขนาดใหญ่เกินไป (1MB)";
                return ("Error");
            }
            else
            {
                if (photo.ContentLength > 0)
                {
                    var fileName = Path.GetFileName(photo.FileName);
                    var path = Path.Combine(Server.MapPath("~/Upload/") + fileName);
                    string i = "/Upload/" + fileName+","+fileName;
                    photo.SaveAs(path);
                    ViewBag.fileName = photo.FileName;
                    if (photo.ContentType.Equals("application/pdf"))
                    {
                        return i;
                    }
                    else
                        
                        return i;
                }
                return ("Error");
            }
        }
    }    
}
         

    

SystemManage/SystemManage/Views/UploadFile/DetailDocument.cshtml
@model SystemManage.Models.DocumentModel
<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js"></script>
    <title>รายละเอียดเอกสาร</title>
    <style>
        input, select, textarea {
            max-width: 2800px;
        }

            textarea.form-control {
                height: 150px;
                resize: none;
            }
    </style>
</head>
<body>
    @using (Ajax.BeginForm("EditDocument", "UploadFileController", new AjaxOptions { HttpMethod = FormMethod.Post.ToString(), OnSuccess = "data" }, new { enctype = "multipart/form-data" }))
    {
        <div class="container">
            <div class="card" style="margin-top: 20px">
                <div class="card-body shadow">
                    <div class="row">
                        <div class="col-sm-12">
                            <label class="label">ชื่อเอกสาร :</label>
                            @Html.HiddenFor(m => m.DocumentID)
                            @{
                                if (Model.CreateBy == Convert.ToInt32(Session["userID"]))
                                {
                                    @Html.TextBoxFor(m => m.DocumentName, new { @class = "form-control" })
                                }
                                else
                                {
                                    @Html.TextBoxFor(m => m.DocumentName, new { @class = "form-control", Readonly = "" })
                                }
                            }
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-sm-12">
                            <div class="form-group">
                                <label for="comment">รายละเอียด:</label>
                                @{
                                    if (Model.CreateBy == Convert.ToInt32(Session["userID"]))
                                    {
                                        @Html.TextAreaFor(m => m.DocumentDetail, new { @class = "form-control" })
                                    }
                                    else
                                    {
                                        @Html.TextAreaFor(m => m.DocumentDetail, new { @class = "form-control", Readonly = "" })
                                    }
                                }

                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-sm-4">
                            <div class="form-group">
                                <label class="label">ไฟล์แนบ :</label>
                                @{
                                    if (Model.CreateBy == Convert.ToInt32(Session["userID"]))
                                    {
                                        @Html.TextBoxFor(m => m.AttachFile, new { type = "file", @class = "form-control-file" })
                                        <a href='@Model.ShowPath' target="_blank">@Model.AttachShow</a>
                                    }
                                    else
                                    {
                                        <a href='@Model.ShowPath' target="_blank">@Model.AttachShow</a>
                                    }
                                }
                            </div>
                        </div>
                    </div>
                    <di v class="row" style="margin-top: 20px;margin-bottom: 20px">
                        <div class="col-sm-10">
                        </div>
                        <div class="col-sm-2">
                            <a href="@Url.Action("ShowDocument","UploadFile")"><button type="button" class="btn btn-outline-danger">ยกเลิก</button></a>
                            @{
                                if (Model.CreateBy == Convert.ToInt32(Session["userID"]))
                                {
                                    <button type="submit" class="btn btn-outline-primary">ยืนยัน</button>
                                }
                            }
                        </div>
                </div>
            </div>
        </div>
    }
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
</body>
</html>

SystemManage/SystemManage/Views/UploadFile/Index.cshtml
@model SystemManage.Models.DocumentModel
<style>
    input, select, textarea {
        max-width: 2800px;
    }
</style>
<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js"></script>
    <title>เพิ่มเอกสาร</title>
</head>
<body>
    @using (Ajax.BeginForm("Index", "UploadFileController", new AjaxOptions { HttpMethod = FormMethod.Post.ToString(), OnSuccess = "data" }, new { enctype = "multipart/form-data" }))
    {
        <div class="container">
            <div class="card" style="margin-top: 50px">
                <div class="card-body shadow">
                    <div class="row">
                        <div class="col-sm-12">
                            <label class="label">@Html.Label("*", new { @style = "color:red" }) ชื่อเอกสาร :</label>
                            @Html.TextBoxFor(m => m.DocumentName, new { @class = "form-control", @placeholder = "กรุณาใส่ชื่อเอกสาร" })
                            @Html.ValidationMessageFor(m => m.DocumentName, "", new { @class = "text-danger" })
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-sm-12">
                            <div class="form-group">
                                <label for="comment">รายละเอียด:</label>
                                @Html.TextAreaFor(m => m.DocumentDetail, new { @class = "form-control", @style = "resize:none;height:150px", @placeholder = "กรุณาใส่รายละเอียด" })
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-sm-12">
                            <div class="form-group">
                                <label class="label">@Html.Label("*", new { @style = "color:red" }) ไฟล์แนบ :</label>
                                @Html.TextBoxFor(m => m.AttachFile, new { type = "file", @class = "form-control-file" })
                                @Html.ValidationMessageFor(m => m.AttachFile, "", new { @class = "text-danger" })
                            </div>
                        </div>
                    </div>
                    <div class="row" style="margin-top: 20px;margin-bottom: 20px">
                        <div class="col-sm-10">
                        </div>
                        <div class="col-sm-2">
                            <a href="@Url.Action("ShowDocument","UploadFile")"><button type="button" class="btn btn-outline-danger" onclick='return confirm("คุณต้องการยกเลิกการทำรายการใช่หรือไม่่")'>ยกเลิก</button></a>
                            <button type="submit" class="btn btn-outline-primary" onclick='return confirm("คุณต้องการยืนยันการทำรายการใช่หรือไม่่")'>ยืนยัน</button>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    }
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
</body>
</html>
@*@using (Html.BeginForm("Process", "UploadFile", FormMethod.Post, new { enctype = "multipart/form-data" }))*@
<script>
    function post(data)
    function post2(data2)
</script>

SystemManage/SystemManage/Views/UploadFile/ShowDocument.cshtml
<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.6.3/css/all.css" integrity="sha384-UHRtZLI+pbxtHCWp1t77Bi1L4ZtiqrqD80Kn4Z8NTSRyMA2Fd33n5dQ8lWUE00s/" crossorigin="anonymous">
@{
    if (Session["userID"] == null && Session["ProjectID"] == null)
    {
        Response.Redirect("~/Login/Index");
    }
}
@{
    ViewBag.Title = "เอกสาร";
    Layout = "~/Views/Shared/_MainMenu.cshtml";
}
@using SystemManage.Models;
@model SystemManage.Models.DocumentModel
<style>
    #sr {
        background-image: url('https://www.w3schools.com/css/searchicon.png');
        background-position: 10px 12px;
        background-repeat: no-repeat;
        width: 100%;
        font-size: 16px;
        padding: 12px 20px 12px 40px;
        border: 1px solid #ddd;
        margin-bottom: 12px;
        border-radius: 18px;
        outline: none;
    }

    th {
        white-space: nowrap;
    }
</style>
<script>
    $(document).ready(function () {
        $("#sr").on("keyup", function () {
            var value = $(this).val().toLowerCase();
            $("#tb tr").filter(function () {
                $(this).toggle($(this).text().toLowerCase().indexOf(value) > -1)
            });
        });
    });
</script>
<div class="card">
    <div class="card-body" style="margin: auto" id="panel">
        <div class="row">
            <div class="col-sm-12 text-center">
                <h1 class="text-center" style="margin-bottom: 20pt">เอกสาร</h1>
            </div>
        </div>
        <div class="row">
            <div class="col-sm-6">
                <div class="input-group mb-3">
                    <div class="input-group-prepend">
                        <span class="input-group-text" id="basic-addon1">ชื่อเอกสาร</span>
                    </div>
                    <input type="text" id="tk" class="form-control" aria-label="Username" aria-describedby="basic-addon1">
                </div>
            </div>
            <div class="col-sm-6">
                <div class="input-group">
                    <label class="label" for="subject" style="margin-right: 10px">ประเภทเอกสาร:</label>
                    <div class="rs-select2 js-select-simple select--no-search " style="width: 100px">
                        <select name="subject">
                            <option>0</option>
                        </select>
                        <div class="select-dropdown"></div>
                    </div>
                </div>
            </div>
        </div>
        <div class="row">
            <div style="margin: auto;margin-top: 20px">
                <button type="button" class="btn btn-primary">Search</button>
                <button type="button" class="btn btn-basic">Clear</button>
            </div>
        </div>
    </div>
</div>

<div class="card">
    <div class="card-body">
        <div class="card">
            <div class="card-body">
                <div class="row">
                    <div class="col-sm-4" style="margin: auto">
                        <h1 style="margin-bottom: 20pt">เอกสาร</h1>
                    </div>
                    <div class="col-sm-6">    </div>
                    <div class="col-sm-1" style="margin: auto">
                        @{
                            if (Model.CreateBy == Convert.ToInt32(Session["userID"]) && Model.Project_Status != 4)
                            {
                                <a href="@Url.Action("Index", "UploadFile")"><button type="button" class="btn btn-outline-success">+ เพิ่มเอกสาร</button></a>
                            }
                        }
                    </div>
                </div>
                <div class="row">
                    <div class="col-sm-9"></div>
                    <div class="col-sm-3"><input type="text" id="sr" onkeyup="myFunction1()" placeholder="ค้นหา"></div>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-sm-12 " style="overflow-x:auto">
                <table class="table table-responsive-sm table-bordered">
                    <thead>
                        <tr class="table-info">
                            <th><center>ดู</center></th>
                            <th><center>ลำดับ</center></th>
                            <th><center>ชื่อเอกสาร</center></th>
                            <th><center>ประเภทของเอกสาร</center></th>
                            <th><center>อ่าน</center></th>
                            @{
                                if (Model.CreateBy == Convert.ToInt32(Session["userID"]))
                                {
                                    <th><center>ลบ</center></th>
                                }
                            }
                        </tr>
                    </thead>
                    <tbody id="tb">
                        @{
                            int i = 1;
                            foreach (var item in (List<DocumentModel>)ViewBag.DataList)
                            {
                                <tr>
                                    <td><center><a href="@item.pathFormView" target="_blank"><i class="fas fa-eye"></i></a></center></td>
                                    <td><center>@i</center></td>
                                    <td><center>@item.DocumentName</center></td>
                                    <td><center>@item.Type</center></td>
                                    <td><center><a href="@Url.Action("DetailDocument",new {DocumentID = item.DocumentID })"><i class="fas fa-book-open"></i></a></center></td>
                                    @{
                                        if (Model.CreateBy == Convert.ToInt32(Session["userID"]))
                                        {
                                            <td><center><a href="@Url.Action("DeleteDocument",new {DocumentID = item.DocumentID })"><i class="fas fa-backspace" onclick='return confirm("คุณต้องการลบข้อมูลใช่หรือไม่่")'></i></a></center></td>
                                        }
                                    }
                                </tr>
                                ++i;
                            }
                        }
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>

@*@{
        Layout = null;
    }
    <!DOCTYPE html>
    <html>
    <head>
        <meta name="viewport" content="width=device-width" />
        <title>Index</title>
    </head>
    <body>
        @using (Html.BeginForm("Process", "UploadFile", FormMethod.Post, new { enctype = "multipart/form-data" }))
        {
            @ViewBag.Error
            <table cellpadding="2" cellspacing="2">
                <tr>
                    <td>Photo</td>
                    <td><input type="file" name="photo" /></td>
                </tr>
                <tr>
                    <td>&nbsp;</td>
                    <td><input type="submit" value="Upload" /></td>
                </tr>
            </table>
        }
    </body>
    </html>*@