SystemManage/SystemManage/Controllers/DefectController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using SystemManage.Database;
using SystemManage.Models;

namespace SystemManage.Controllers
{
    public class DefectController : Controller
    {
        Entities db = new Entities();
        // GET: Defect
        public ActionResult AddDefect()
        {
            if ((Session["userID"]) == null)
            {
                return RedirectToAction("Index", "Login");
            }
            if (Convert.ToInt32(Session["Defect_SIT"]) == 1)
            {
                DefectModel model = new DefectModel();
                int SIT_ID = Convert.ToInt32(Session["SIT_ID"]);
                var SIT = db.SITs.Where(m => m.SIT_ID == SIT_ID).FirstOrDefault();
                var user = db.Users.Where(m => m.User_ID == SIT.Dev_ID).FirstOrDefault();
                model.TaskName = SIT.Name;
                model.DevName = user.User_Name;
                return View(model);
            }
            else
            {
                int SubID = Convert.ToInt32(Session["SubID"]);
                DefectModel model = new DefectModel();
                var item = db.SubTasks.Where(m => m.SubID == SubID).FirstOrDefault();
                var item2 = db.Tasks.Where(m => m.TaskID == item.TaskID).FirstOrDefault();
                var item3 = db.Users.Where(m => m.User_ID == item.SubDevID).FirstOrDefault();
                model.Sub_ID = SubID;
                model.SubTaskName = item.SubName;
                model.TaskName = item2.TaskName;
                model.DevName = item3.User_Email;
                return View(model);
            }
        }
        [HttpPost]
        public ActionResult AddDefect(DefectModel model)
        {
            if (Convert.ToInt32(Session["Defect_SIT"]) == 1)
            {
                if (model.DetailList[0] != "")
                {
                    int projectID = Convert.ToInt32(Session["ProjectID"]);
                    Defect d = new Defect();
                    SubTask st = new SubTask();
                    int SIT_ID = Convert.ToInt32(Session["SIT_ID"]);
                    var count = model.DetailList.Count;
                    if (count > 1)
                    {
                        for (int i = 0; i < count; ++i)
                        {
                            d.Sub_ID = SIT_ID;
                            d.Detail = model.DetailList[i].ToString();
                            d.SendDate = model.SendDateList[i];
                            d.Status = 0;
                            d.CreateDate = DateTime.Now;
                            d.CreateBy = Convert.ToInt32(Session["userID"]);
                            d.Project_ID = projectID;
                            if (model.AttachFileList[i] != null)
                            {
                                var Upload = Upload_Defect(model.AttachFileList[i]);
                                string[] txt = Upload.Split(",".ToCharArray());
                                d.AttachFile = txt[0];
                                d.AttachShow = txt[1];
                            }
                            db.Defects.Add(d);
                            db.SaveChanges();
                            var SIT = db.SITs.Where(m => m.SIT_ID == SIT_ID).FirstOrDefault();
                            SIT.Defect_SIT = 1;
                            SIT.Status = 4;
                            db.SaveChanges();
                            var Email = db.Users.Where(m => m.User_ID == d.CreateBy).FirstOrDefault();
                            var Sendto = db.Users.Where(m => m.User_ID == SIT.Dev_ID).FirstOrDefault();
                            string sender = Email.User_Email.ToString();
                            //string sender = "systemmanage59346@gmail.com";
                            string subject = "Defect หัวข้อ" + st.SubName;
                            string receiver = Sendto.User_Email.ToString();
                            //string receiver = "pattanapon2538@outlook.com";
                            string mess = "มีข้อผิดพลาดในหัวข้อ" + st.SubName;
                            InboxController ms = new InboxController();
                            ms.SendEmail(receiver, subject, mess, sender);
                        }
                    }
                    else
                    {
                        d.Sub_ID = SIT_ID;
                        d.Detail = model.DetailList[0].ToString();
                        d.SendDate = model.SendDateList[0];
                        d.Status = 0;
                        d.CreateDate = DateTime.Now;
                        d.CreateBy = Convert.ToInt32(Session["userID"]);
                        d.Project_ID = projectID;
                        if (model.AttachFileList[0] != null)
                        {
                            var Upload = Upload_Defect(model.AttachFileList[0]);
                            string[] txt = Upload.Split(",".ToCharArray());
                            d.AttachFile = txt[0];
                            d.AttachShow = txt[1];
                        }
                        db.Defects.Add(d);
                        db.SaveChanges();
                        var SIT = db.SITs.Where(m => m.SIT_ID == SIT_ID).FirstOrDefault();
                        SIT.Defect_SIT = 1;
                        SIT.Status = 4;
                        db.SaveChanges();
                        var Email = db.Users.Where(m => m.User_ID == d.CreateBy).FirstOrDefault();
                        var Sendto = db.Users.Where(m => m.User_ID == SIT.Dev_ID).FirstOrDefault();
                        string sender = Email.User_Email.ToString();
                        //string sender = "systemmanage59346@gmail.com";
                        string subject = "Defect หัวข้อ" + st.SubName;
                        string receiver = Sendto.User_Email.ToString();
                        //string receiver = "pattanapon2538@outlook.com";
                        string mess = "มีข้อผิดพลาดในหัวข้อ" + st.SubName;
                        InboxController ms = new InboxController();
                        ms.SendEmail(receiver, subject, mess, sender);
                    }
                    return RedirectToAction("ShowDefect");
                }
                return View(new DefectModel
                {
                    Error_Detail = "กรุณาใส่ข้อมูลให้ครบถ้วน"
                });
            }
            else
            {
                if (model.DetailList[0] != "")
                {
                    int projectID = Convert.ToInt32(Session["ProjectID"]);
                    Defect d = new Defect();
                    SubTask st = new SubTask();
                    int SubID = Convert.ToInt32(Session["SubID"]);
                    var count = model.DetailList.Count;
                    if (count > 1)
                    {
                        for (int i = 0; i < count; ++i)
                        {
                            d.Sub_ID = model.Sub_ID;
                            d.Detail = model.DetailList[i].ToString();
                            d.SendDate = model.SendDateList[i];
                            d.Status = 0;
                            d.CreateDate = DateTime.Now;
                            d.CreateBy = Convert.ToInt32(Session["userID"]);
                            d.Project_ID = projectID;
                            if (model.AttachFileList[i] != null)
                            {
                                var Upload = Upload_Defect(model.AttachFileList[i]);
                                string[] txt = Upload.Split(",".ToCharArray());
                                d.AttachFile = txt[0];
                                d.AttachShow = txt[1];
                            }
                            db.Defects.Add(d);
                            db.SaveChanges();
                            var s = db.SubTasks.Where(m => m.SubID == model.Sub_ID).FirstOrDefault();
                            s.HaveDefect = 1;
                            s.SubStatus = 5;
                            s.SubPercent = 25;
                            db.SaveChanges();
                            var Email = db.Users.Where(m => m.User_ID == d.CreateBy).FirstOrDefault();
                            var Sendto = db.Users.Where(m => m.User_ID == s.SubDevID).FirstOrDefault();
                            string sender = Email.User_Email.ToString();
                            //string sender = "systemmanage59346@gmail.com";
                            string subject = "Defect หัวข้อ" + st.SubName;
                            string receiver = Sendto.User_Email.ToString();
                            //string receiver = "pattanapon2538@outlook.com";
                            string mess = "มีข้อผิดพลาดในหัวข้อ" + st.SubName;
                            InboxController ms = new InboxController();
                            ms.SendEmail(receiver, subject, mess, sender);
                        }
                    }
                    else
                    {
                        d.Sub_ID = model.Sub_ID;
                        d.Detail = model.DetailList[0].ToString();
                        d.SendDate = model.SendDateList[0];
                        d.Status = 0;
                        d.CreateDate = DateTime.Now;
                        d.CreateBy = Convert.ToInt32(Session["userID"]);
                        d.Project_ID = projectID;
                        if (model.AttachFileList[0] != null)
                        {
                            var Upload = Upload_Defect(model.AttachFileList[0]);
                            string[] txt = Upload.Split(",".ToCharArray());
                            d.AttachFile = txt[0];
                            d.AttachShow = txt[1];
                        }
                        db.Defects.Add(d);
                        db.SaveChanges();

SystemManage/SystemManage/Views/Defect/AddDefect.cshtml
@{
    if (Session["userID"] == null && Session["ProjectID"] == null)
    {
        Response.Redirect("~/Login/Index");
    }
}
@{
    ViewBag.Title = "AddDefect";
    @model SystemManage.Models.DefectModel
}
<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js"></script>
    <!-- <script src="https://code.jquery.com/jquery-1.12.4.js"></script>
    <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script> -->
    <script>
        //***scritpt datepicker***//
        //$(function () {
        //    $("#datepicker1").datepicker();
        //    $("#datepicker2").datepicker();
        //    $("#datepicker3").datepicker();
        //    $("#datepicker4").datepicker();
        //    $("#datepicker5").datepicker();
        //    $("#datepicker6").datepicker();
        //    $("#datepicker7").datepicker();
        //    $("#datepicker8").datepicker();
        //    $("#datepicker9").datepicker();
        //    $("#datepicker10").datepicker();
        //});
        //***//
        //***script addsubtask***//
        $(document).ready(function () {
            var i = 1;
            $("#add").click(function () {
                i++;
                var domElement = $('<div class ="card" id="new"><dic class ="card-body"><div class="row"> <div class="col-sm-12"><div class="form-group"> <label for="comment">@Html.Label("*", new { @style = "color:red" }) รายละเอียดข้อผิดพลาด:</label> <label style="float:right"><a href="#div" id="cancel"><img src="/icon/cancel.png" width="24px" height="24px"></a></label> @Html.Raw(Ajax.JavaScriptStringEncode(Html.TextAreaFor(m => m.DetailList, new { @class = "form-control", @type = "TextArea", style = "height:100px" }).ToHtmlString())) </div> </div></div> <div class="row"> <div class="col-sm-6"> <div class="input-group">  <label class="label" style="margin-right: 10px">@Html.Label("*", new { @style = "color:red" }) กำหนดส่ง :</label>@Html.TextBoxFor(m => m.SendDateList, new { @class = "form-control", @type = "date" })@Html.ValidationMessageFor(m => m.SendDateList, "", new { @class = "text-danger" }) </div> </div>  <div class="col-sm-6"> <div class="input-group"> <label class="label">ไฟล์แนบ :</label>@Html.TextBoxFor(m => m.AttachFileList, new { type = "file", @class = "form-control-file" }) </div> </div> </div></div> </div>');
                $(this).parent('div').before(domElement);
            });
        });
        //***//
        //***script deletesubtask***//
        $(document).on('click', '#cancel', function () {
            var c = confirm("ยืนยันการลบที่จะลบ Defect นี้");
            if (c == true) {
                $(this).parentsUntil("#new").parent().remove();
            }
        });
        //***//
        ////***script confrimrefresh***//
        //window.onbeforeunload = function () {
        //    return "ข้อมูลไม่ได้บันทึก";
        //};
                                    //***//
    </script>
    <!-- end datepicker script -->
    <style>
        select, textarea {
            max-width: 2800px;
            height: 150px
        }

            textarea.form-control {
                height: 150px;
                resize: none;
            }
    </style>
    <title>ข้อผิดพลาด</title>
</head>
<body>
    @using (Ajax.BeginForm("AddDefect", "Defect", new AjaxOptions { HttpMethod = FormMethod.Post.ToString() }, new { enctype = "multipart/form-data" }))
    {
        <div class="container">
            <div class="row">
                <div class="col-sm-12 text-center">
                    <h1 class="text-center" style="margin-top: 20pt">ข้อผิดพลาด</h1>
                </div>
            </div>
            <div class="card shadow" style="margin-top: 10px;margin-bottom: 50px">
                <div class="card-body">
                    <div class="row">
                        <div class="col-sm-6">
                            <div class="form-group">
                                <label for="taskname">ชื่องาน :</label>
                                @Html.TextBoxFor(m => m.TaskName, new { @class = "form-control", ReadOnly = "" })
                            </div>
                        </div>
                        @{
                            if (Convert.ToInt32(Session["Defect_SIT"]) != 1)
                            {
                                <div class="col-sm-6">
                                    <div class="form-group">
                                        <label for="taskname">ชื่องานรอง :</label>
                                        @Html.HiddenFor(m => m.Sub_ID)
                                        @Html.TextBoxFor(m => m.SubTaskName, new { @class = "form-control", Readonly = "" })

                                    </div>
                                </div>
                            }
                        }
                        <div class="col-sm-4">
                            <div class="input-group">
                                <label class="label" style="margin-right: 10px">ผู้พัฒนา :</label>
                                @Html.TextBoxFor(m => m.DevName, new { readOnreadOnly = true, @class = "form-control", ReadOnly = "" })
                            </div>
                        </div>
                    </div>
                    <div class="card" style="margin-top:20px">
                        <div class="card-body">
                            <div class="row">
                                <div class="col-sm-12">
                                    <div class="form-group">
                                        <label for="comment">@Html.Label("*", new { @style = "color:red" }) รายละเอียดข้อผิดพลาด:</label>
                                        @Html.TextAreaFor(m => m.DetailList, new { @class = "form-control" })
                                        @Html.ValidationMessageFor(m => m.DetailList, Model.Error_Detail, new { @class = "text-danger" })
                                    </div>
                                </div>
                            </div>
                            <div class="row">
                                <div class="col-sm-6">
                                    <div class="input-group">
                                        <label class="label" style="margin-right: 10px">@Html.Label("*", new { @style = "color:red" }) กำหนดส่ง :</label>
                                        @Html.TextBoxFor(m => m.SendDateList, new { @class = "form-control", @type = "date" })
                                        @Html.ValidationMessageFor(m => m.SendDateList, "", new { @class = "text-danger" })
                                    </div>
                                </div>
                                <div class="col-sm-6">
                                    <div class="input-group">
                                        <label class="label">ไฟล์แนบ :</label>
                                        @Html.TextBoxFor(m => m.AttachFileList, new { type = "file", @class = "form-control-file" })
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div style="text-align: center;margin-top: 20px">
                        <a href="#div" id="add"><cneter><img src="~/icon/plus.png" width="42px" height="42px"></a>
                    </div>
                    <div class="row" style="margin-top: 20px;margin-bottom: 20px">
                        <div class="col-sm-10">
                        </div>
                        <div class="col-sm-2">
                            <a href="@Url.Action("ShowTask", "Task", new { SubTask = Session["SubTask"] })"><button type="button" class="btn btn-outline-danger" onclick='return("คุณต้องการยกเลิกการทำรายการใช่หรือไม่่")'>ยกเลิก</button></a>
                            <button type="submit" class="btn btn-outline-primary" onclick='return confirm("คุณต้องการยินยันการทำรายการใช่หรือไม่่")'>ยืนยัน</button>

                        </div>
                    </div>
                </div>
            </div>
        </div>
    }
</body>
</html>

SystemManage/SystemManage/Views/Defect/Defect_Dev.cshtml
@model SystemManage.Models.DefectModel
@using SystemManage.Models
@{
    if (Session["userID"] == null && Session["ProjectID"] == null)
    {
        Response.Redirect("~/Login/Index");
    }
}
@{
    ViewBag.Title = "DetailDefect";
}
<style>
    textarea.form-control {
        height: 100px;
        resize: none;
    }
</style>
<body>
    @using (Html.BeginForm("SeveData", "Defect", FormMethod.Post))
    {
        @Html.AntiForgeryToken()
        <div class="container">
            <div class="row">
                <div class="col-sm-12 text-center">
                    <h1 class="text-center" style="margin-top: 20pt">ข้อผิดพลาด</h1>
                </div>
            </div>
            <div class="card shadow" style="margin-top: 50px;margin-bottom: 50px">
                <div class="card-body">
                    <div class="row">
                        <div class="col-sm-6">
                            <div class="form-group">
                                <label for="taskname">ชื่องาน :</label>
                                @Html.TextBoxFor(m => m.TaskName, new { @class = "form-control", @readonly = "" })
                            </div>
                        </div>
                        <div class="col-sm-6">
                            <div class="form-group">
                                <label for="taskname">ชื่องานรอง :</label>
                                @Html.HiddenFor(m => m.Sub_ID)
                                @Html.TextBoxFor(m => m.SubTaskName, new { @class = "form-control", @readonly = "" })
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-sm-6">
                            <div class="input-group">
                                <label class="label" style="margin-right: 10px">ผู้พัฒนา :</label>
                                @Html.TextBoxFor(m => m.DevName, new { @class = "form-control", @readonly = "" })
                            </div>
                        </div>
                    </div>
                    @{
                        foreach (var item in (List<DefectModel>)ViewBag.DataList)
                        {
                            <div class="row">
                                <div class="col-sm-12">
                                    <div class="form-group">
                                        <label for="comment">รายละเอียดข้อผิดพลาด:</label>
                                        @Html.TextAreaFor(m => item.Detail, new { @class = "form-control", @type = "TextArea", @readonly = "" })
                                    </div>
                                </div>
                            </div>
                            <div class="row">
                                <div class="col-sm-4">
                                    <div class="input-group">
                                        <label class="label" style="margin-right: 10px">กำหนดส่ง:</label>
                                        @Html.TextBoxFor(m => item.SendDate, "{0:MM/dd/yyyy}", new { @class = "form-control", @readonly = "" })
                                    </div>
                                </div>
                                @{
                                    if (item.Status == 0)
                                    {
                                        <div class="col-sm-4">
                                            <div class="input-group">
                                                <label class="label" for="subject" style="margin-right: 10px">สถานะ :</label>
                                                <div class="rs-select2 js-select-simple select--no-search ">
                                                    <label>อยู่ระหว่างการตอบรับ</label>
                                                </div>
                                            </div>
                                        </div>
                                        <div class="col-sm-4">
                                            <div class="form-group">
                                                <label class="label">ไฟล์แนบ :</label>
                                                <a href='@item.Path_Defect' target="_blank">@item.AttachShow</a>
                                            </div>
                                        </div>
                                    }
                                    else if (item.Status == 1)
                                    {
                                        <div class="col-sm-4">
                                            <div class="input-group">
                                                <label class="label" for="subject" style="margin-right: 10px">สถานะ :</label>
                                                <div class="rs-select2 js-select-simple select--no-search ">
                                                    <label>กำลังแก้ไข</label>
                                                </div>
                                            </div>
                                        </div>
                                        <div class="col-sm-4">
                                            <div class="form-group">
                                                <label class="label">ไฟล์แนบ :</label>
                                                <a href='@item.Path_Defect' target="_blank">@item.AttachShow</a>
                                            </div>
                                        </div>
                                    }
                                    else if (item.Status == 2)
                                    {
                                        <div class="col-sm-4">
                                            <div class="input-group">
                                                <label class="label" for="subject" style="margin-right: 10px">สถานะ :</label>
                                                <div class="rs-select2 js-select-simple select--no-search ">
                                                    <label>แก้ไขแล้ว</label>
                                                </div>
                                            </div>
                                        </div>
                                        <div class="col-sm-4">
                                            <div class="form-group">
                                                <label class="label">ไฟล์แนบ :</label>
                                                <a href='@item.Path_Defect' target="_blank">@item.AttachShow</a>
                                            </div>
                                        </div>
                                    }
                                    else if (item.Status == 3)
                                    {
                                        <div class="col-sm-4">
                                            <div class="input-group">
                                                <label class="label" for="subject" style="margin-right: 10px">สถานะ :</label>
                                                <div class="rs-select2 js-select-simple select--no-search ">
                                                    <label>ปิด</label>
                                                </div>
                                            </div>
                                        </div>
                                        <div class="col-sm-4">
                                            <div class="form-group">
                                                <label class="label">ไฟล์แนบ :</label>
                                                <a href='@item.Path_Defect' target="_blank">@item.AttachShow</a>
                                            </div>
                                        </div>
                                    }
                                    else if (item.Status == 4)
                                    {
                                        <div class="col-sm-4">
                                            <div class="input-group">
                                                <label class="label" for="subject" style="margin-right: 10px">สถานะ :</label>
                                                <div class="rs-select2 js-select-simple select--no-search ">
                                                    <label>แก้ไขใหม่</label>
                                                </div>
                                            </div>
                                        </div>
                                        <div class="col-sm-4">
                                            <div class="form-group">
                                                <label class="label">ไฟล์แนบ :</label>
                                                <a href='@item.Path_Defect' target="_blank">@item.AttachShow</a>
                                            </div>
                                        </div>
                                    }
                                }
                                @Html.HiddenFor(m => m.CreateBy)
                            </div>
                        }
                    }
                    <div class="row" style="margin-top: 20px;margin-bottom: 20px">
                        <div class="col-sm-10">
                        </div>
                        <div class="col-sm-2">
                            <a href="@Url.Action("ShowDefect","Defect")"><button type="button" class="btn btn-outline-danger">กลับ</button></a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    }
</body>
<style>
    input, select, textarea {
        max-width: 2800px;
    }
</style>